### ISSUE TITLE
Crosscite styles and locales are not loading

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#238] opened 2019-10-02 13:20 UTC
### Expected Behaviour

Crosscite generates citations styles

### Current Behaviour

Dropdown menu is not working 

### Steps to Reproduce

1. navigate to https://citation.crosscite.org/
2. enter a doi
3. try to select a citation style from the dropdown menu
4. no response

### Context (Environment)

 Production

### Possible Implementation

LikeBe the first to like this

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ykeb)

**Comment by richardhallett** [comment] 2019-10-04 09:44
Closing as appears to be working now.

**Comment by richardhallett** [comment] 2019-10-10 09:44
Issue re-occuring.

**Comment by richardhallett** [comment] 2019-10-14 15:39
The issue is intermittent, it seems not restricted to just the citation styles, can also occur when attempting to just lookup the result of a DOI, the 500 appears to be generic error failure on the server.
I've added logging into DataDog now, but so far nothing obvious for the intermittent behaviour.

**Comment by richardhallett** [comment] 2019-10-15 09:17
This was a single failed instance running on our shared infrastructure with solr, that specific instance had eaten all the disk space.
I freed the space, all working now as expected.

**Closed by richardhallett** 2019-10-15 09:17 UTC
Labels: bug
