### ISSUE TITLE
Fabrica test : prefix lookup not working

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#531] opened 2021-03-31 16:26 UTC
#### Expected Behaviour

Prefixes can be assigned to members and repositories 

#### Current Behaviour

Prefix do not appear in the lookup

#### Steps to Reproduce

cannot assign these 3 prefixes https://doi.test.datacite.org/providers/odfp

to this repository https://doi.test.datacite.org/repositories/odfp.open-journals

### Context (Environment)

Fabrica test

**Comment by MaryHirsch** [comment] 2021-04-12 13:40
@richardhallett looks like this happens specifically when existing prefixes are already assigned at member level but don't appear in drop down at repository level another example https://doi.test.datacite.org/repositories/odfp.open-journals

**Comment by richardhallett** [comment] 2021-04-15 14:51
After investigation, the look up here is working, the problem is actually prefixes being shown on the organisation level account.
These prefixes are not available because they actually do belong to a repository, these repostories are deleted and they've not been unassigned.

So the solution to this specific issue is to assign new prefixes for the repository to use. 

I've raised a seperate issue that is more specific around prefixes belonging to deleted repositories. https://github.com/datacite/bracco/issues/535

I will close this issue as there is no bug around lookups here, and we can handle the specific repository on test as a support issue.

**Closed by richardhallett** 2021-04-15 14:51 UTC
Labels: bug
