### ISSUE TITLE
nameType attribute is required when updating DOI via file upload

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#234] opened 2019-10-01 09:18 UTC
### Expected Behaviour

The file upload indicates whether the information entered is correct or not

### Current Behaviour

When updating a DOI via file upload, the nameType is required

### Steps to Reproduce

1. create a draft doi via file upload but don't include nameType
2. try to update to findable state
3. the update won't work unless the nameType is added or the creator information is adjusted in the form

### Context (Environment)

Fabrica production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_157r7)

**Comment by MaryHirsch** [comment] 2019-10-01 09:29
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resource xmlns="http://datacite.org/schema/kernel-3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd">
  <identifier identifierType="DOI">10.14283/JNHRS.2019.7</identifier>
  <creators>
    <creator>
      <creatorName>L.J.M Hoek
</creatorName>
    </creator>
    <creator>
      <creatorName>J.C.M. van Haastregt
</creatorName>
    </creator>
    <creator>
      <creatorName>E. de Vries
</creatorName>
    </creator>
    <creator>
      <creatorName>R. Backhaus
</creatorName>
    </creator>
    <creator>
      <creatorName>J.P.H. Hamers
</creatorName>
    </creator>
    <creator>
      <creatorName>H. Verbeek</creatorName>
    </creator>
  </creators>
  <titles>
    <title>Factors Influencing Autonomy of Nursing Home  Residents with Dementia : The perception of Family Caregivers</title>
  </titles>
  <publisher>The Journal of Nursing Home Research Science (JNHRS)</publisher>
  <publicationYear>2019</publicationYear>
  <subjects>
    <subject>Autonomy
</subject>
    <subject>nursing homes
</subject>
    <subject>dementia,
</subject>
    <subject>amily caregivers</subject>
  </subjects>
  <language>eng</language>
  <resourceType resourceTypeGeneral="Text">JournalArticle </resourceType>
  <version>1</version>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="IsPartOf">10.14283/jnhrs.2012.0</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="ISSN" relationType="IsPartOf">2496-0799</relatedIdentifier>
  </relatedIdentifiers>
  <descriptions>
    <description descriptionType="Abstract">Background: Being able to live the life you want to live within a nursing home might be challenging for residents with dementia, as they become dependent on others in achieving autonomy. However, little is known about which factors support or impede resident autonomy within nursing homes. Objectives: The purpose of this study was to gain insight into factors that support or impede autonomy for nursing home residents with dementia, from the perspective of their family caregivers. Design: A qualitative study was conducted. Setting: Five psychogeriatric nursing home wards within three care organizations in the Netherlands. Participants: 30 family caregivers. Measurements: Semi-structured interviews were held and a qualitative thematic approach was used. Findings: This study identified several factors that seemed to influence resident autonomy within six themes: activities; personal approach; visits from family and friends; being part of a group; physical environment; and organization of care. Within these themes, factors were mentioned that could either support or impede resident autonomy. For example, being socially engaged with family and fellow residents and participation in meaningful activities were supporting factors. The inability to go outside when wished or having inadequate private space were impeding factors. Overall, daily life was mostly organized from a communal and task-centered perspective instead of adaptation to individual preferences. Conclusions: The current study suggests that in order to improve the support of resident autonomy, nursing homes should focus on flexibility in providing care, finding ways to offer meaningful activities, and stimulating resident’s social environment to continue social traditions.</description>
  </descriptions>
</resource>
```

**Comment by richardhallett** [comment] 2020-02-03 14:27
Duplicate of #265, track on that ticket as user is also monitoring there.

**Closed by richardhallett** 2020-02-03 14:27 UTC
Labels: bug
