### ISSUE TITLE
Validation error for Funding References not shown in UI when changing from draft to findable

### ISSUE THREAD

**Issue by lizkrznarich** [datacite/bracco#564] opened 2021-08-26 16:37 UTC
## Expected Behaviour
If optional fields within Funding References have values, but required fields do not, show an error message in the UI

## Current Behaviour
No validation error is shown and user can click Create/Update DOI button. This results in 422 error with message ```{"errors":[{"source":"funderName","uid":"10.21231/2rnq-j208","title":"DOI 10.21231/2rnq-j208: [facet 'minLength'] The value has a length of '0'; this underruns the allowed minimum length of '1'. at line 28, column 0"}]}``` in the console, but no error message is displayed in the UI. 

## Steps to Reproduce
- Create a draft DOI with a Funding Reference that only has values in optional fields, ex only a value in Award number.
- Using the update form, set state to Findable and click Update DOI

## Context (Environment)
Fabrica - reproduced in Test and Prod

## Screenshots
<img width="1132" alt="Screen Shot 2021-08-26 at 11 31 37 AM" src="https://user-images.githubusercontent.com/8026886/131001443-ac2b255d-6cc4-4c22-bab8-32e1a393e002.png">
<img width="1149" alt="Screen Shot 2021-08-26 at 11 35 07 AM" src="https://user-images.githubusercontent.com/8026886/131001456-dc95a0ff-45c0-4983-ab60-dc086e328752.png">

## Further details
Test env example (created by Liz) https://doi.test.datacite.org/dois/10.81009%2Fshxp-rq33
Front ticket reporting issue in prod https://app.frontapp.com/open/cnv_a476jo5

## Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3witx)

**Comment by codycooperross** [comment] 2023-09-28 20:17
I believe this is a duplicate of datacite/bracco#729 and is closed by datacite/bracco#807 —does that seem right, @kaysiz ?

**Comment by kaysiz** [comment] 2023-09-28 20:31
@codycooperross that is correct, I just tested. I will close it.

**Closed by kaysiz** 2023-09-28 20:31 UTC
Labels: bug
