### ISSUE TITLE
Organization logos don't appear in test

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#466] opened 2020-09-28 10:45 UTC
### Expected Behaviour

test and production are the same

### Current Behaviour

member logos do not appear

### Steps to Reproduce

1. https://doi.test.datacite.org/providers/akristia

![Screen Shot 2020-09-28 at 12 44 16](https://user-images.githubusercontent.com/44582654/94423095-606f0280-0188-11eb-87a2-2b13104d6af5.png)

### Context (Environment)

Fabrica test

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o47p)

**Comment by kjgarza** [comment] 2020-10-05 07:21
@MaryHirsch Logos files are separated in different storages (s3 buckets) for each environment. you will need to upload the logo in `test`  if you want to see the logo there.

**Comment by mfenner** [comment] 2020-10-05 07:25
@kjgarza please take a look at the configuration in the test system, the s3 part may not be properly configured.

**Comment by mfenner** [comment] 2020-10-14 13:57
@kjgarza have you confirmed that this now works in Fabrica Test? It doesn't work for me.

**Comment by mfenner** [comment] 2020-10-14 16:36
Uploading a new logo for member ardc doesn't work for me. The old logo remains after hitting save.

**Comment by kjgarza** [comment] 2020-10-15 07:22
I think there is a small delay when replacing a logo because of caching. 

I have seen ardc and it seem the change already took effect. 
I think you are replacing an existing logo not uploading a brand new logo. The latter is instantaneous from my testing, the former might be slower because of S3 object invalidation. Maybe, I can modify for the objects expiration time in the S3 bucket  (Maximum TTL) but we have the same configuration in production.

**Comment by mfenner** [comment] 2020-10-15 07:26
I think the user expects to see the logo that he/she has just uploaded. To avoid caching each logo has a query parameter attached, maybe there is something wrong with that workflow. But I see that the same happens in production. I suggest to open a new issue to look into that (not assigned to anyone yet) and close this issue.

**Comment by kjgarza** [comment] 2020-10-15 07:37
using https://github.com/datacite/bracco/issues/470 to look a replacement

**Closed by kjgarza** 2020-10-15 07:37 UTC
Labels: bug
